### ISSUE TITLE
build 后的代码， 访问申请单只读view接口(/workflow/space/${spaceId}/view/readonly/${instanceId})报错：`fromString` is not a supported option

### ISSUE THREAD

**Issue by baozhoutao** [steedos/creator#1367]
{ error:
   { DefaultsError: `fromString` is not a supported option
       at DefaultsError.get (eval at <anonymous> (C:\srv\github\steedos-project-
piccamc\node_modules\uglify-js\tools\node.js:20:1), <anonymous>:71:23)
       at formatError (internal/util/inspect.js:818:16)
       at formatRaw (internal/util/inspect.js:626:16)
       at formatValue (internal/util/inspect.js:509:10)
       at formatProperty (internal/util/inspect.js:1071:11)
       at formatRaw (internal/util/inspect.js:727:11)
       at formatValue (internal/util/inspect.js:509:10)
       at inspect (internal/util/inspect.js:189:10)
       at Object.formatWithOptions (util.js:164:18)
       at Console.(anonymous function) (console.js:191:15)
       at Console.log (console.js:202:31)
       at Object.SpacebarsCompiler._beautify (packages\spacebars-compiler.js:135
9:23)
       at Object.SpacebarsCompiler.codeGen (packages\spacebars-compiler.js:1337:
28)
       at Object.SpacebarsCompiler.compile (packages\spacebars-compiler.js:1258:
28)
       at Object.compile [as getInstanceView] (meteor://�app/packages/steedos_w
orkflow/client/lib/instance_readonly_template.coffee:462:39)
       at Object.getInstanceView (meteor://�app/packages/steedos_workflow/clien
t/lib/instance_readonly_template.coffee:565:34)
     message: '`fromString` is not a supported option',
     defs:
      { compress: {},
        enclose: false,
        ie8: false,
        keep_fnames: false,
        mangle: {},
        nameCache: null,
        output: {},
        parse: {},
        rename: undefined,
        sourceMap: false,
        timings: false,
        toplevel: false,
        warnings: false,
        wrap: false } } }

**Comment by baozhoutao** [comment]
da74728f8313d5b31a3ae1d8c9a97a82fb8c3829
