### ISSUE TITLE
空库跑creator，每次切换到首页服务端都报错

### ISSUE THREAD

**Issue by yinlianghui** [steedos/creator#1597]
```
Error: Unexpected character at 122
I20200203-13:23:17.755(8)?     at /Users/yin/Documents/GitHub/creator/node_modules/odata-v4-parser/lib/parser.js:20:19
I20200203-13:23:17.756(8)?     at Object.query (/Users/yin/Documents/GitHub/creator/node_modules/odata-v4-parser/lib/parser.js:40:93)
```
![image](https://user-images.githubusercontent.com/6219465/73627824-1bdaa800-4689-11ea-88fc-795ad64b7b26.png)

**Comment by yinlianghui** [comment]
每次切换到首页就会报错，估计是首页有过滤条件在报错了

**Comment by yinlianghui** [comment]
升级到最新版本的app-contracts包就好了
