### ISSUE TITLE
服务端报错  MongoError: ns not found

### ISSUE THREAD

**Issue by steedos** [steedos/creator#276]
2018-04-01 21:59:10 951: MongoError: ns not found
    at Object.Future.wait (/srv/creator/bundle/programs/server/node_modules/fibers/future.js:449:15)
    at [object Object].<anonymous> (packages/meteor.js:209:22)
    at [object Object].MongoConnection.(anonymous function) [as dropCollection] (packages/mongo/mongo_driver.js:742:49)
    at Object.Creator.Objects.objects.triggers.after.remove.server.objects.todo (packages/steedos_object-database/models/object.coffee:162:49)
    at Object.todoWrapper (packages/steedos_objects/lib/triggers.coffee:9:23)
    at packages/matb33_collection-hooks.js:574:20
    at Array.forEach (native)
    at Function._.each._.forEach (packages/underscore.js:139:11)
    at packages/matb33_collection-hooks.js:573:11
    at Array.forEach (native)
    - - - - -
    at Function.MongoError.create (/srv/creator/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/error.js:31:11)
    at /srv/creator/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:497:72
    at authenticateStragglers (/srv/creator/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:443:16)
    at [object Object].messageHandler (/srv/creator/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:477:5)
    at Socket.<anonymous> (/srv/creator/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:331:22)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:536:20)

**Comment by baozhoutao** [comment]
此问题可能是object.triggers执行多次导致

**Comment by baozhoutao** [comment]
未能重现此问题
