### ISSUE TITLE
附件下载报错，导致服务重启

### ISSUE THREAD

**Issue by baozhoutao** [steedos/creator#75]
TypeError: The header content contains invalid characters
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:363:13)
    at ServerResponse.res.setHeader (C:\Users\dell\AppData\Local\.meteor\packages\webapp\1.3.17\npm\node_modules\connect\lib\patch.js:134:22)
    at packages\cfs_http-methods.js:622:17
    at Function._.each._.forEach (packages\underscore.js:147:22)
    at packages\cfs_http-methods.js:618:11

**Comment by baozhoutao** [comment]
[工程合同流程步骤名及字段(2).xlsx](https://github.com/steedos/creator/files/1613805/2.xlsx)

**Comment by yinlianghui** [comment]
经测试，附件中有中文字符就会报错
